apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp
        image: praggya/myflaskapp:latest
        automountServiceAccountToken: false
        imagePullPolicy: Always
        resources:
        limits:
          memory: 100Mi
        ports:
        - containerPort: 5000
